//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCISM_WBRMSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WBRMSystemEntities : DbContext
    {
        public WBRMSystemEntities()
            : base("name=WBRMSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barcode> Barcodes { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Cart_Item> Cart_Item { get; set; }
        public virtual DbSet<Condition> Conditions { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Item_History> Item_History { get; set; }
        public virtual DbSet<ItemCategory> ItemCategories { get; set; }
        public virtual DbSet<ItemSubCategory> ItemSubCategories { get; set; }
        public virtual DbSet<Junk_Item> Junk_Item { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<Reservation_Cart> Reservation_Cart { get; set; }
        public virtual DbSet<Reservation_Cart_Room> Reservation_Cart_Room { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Room_Schedule> Room_Schedule { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Temp_Signup> Temp_Signup { get; set; }
        public virtual DbSet<Temp_StocksbyFacility> Temp_StocksbyFacility { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Transaction_Status> Transaction_Status { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<added_today_vw> added_today_vw { get; set; }
        public virtual DbSet<borrowed_items_vw> borrowed_items_vw { get; set; }
        public virtual DbSet<Cart_Items_vw> Cart_Items_vw { get; set; }
        public virtual DbSet<damaged_items_vw> damaged_items_vw { get; set; }
        public virtual DbSet<Item_Name_vw> Item_Name_vw { get; set; }
        public virtual DbSet<item_vw> item_vw { get; set; }
        public virtual DbSet<Request_vw> Request_vw { get; set; }
        public virtual DbSet<rooms_vw> rooms_vw { get; set; }
        public virtual DbSet<User_Details_vw> User_Details_vw { get; set; }
    
        public virtual int Ass_sp(Nullable<int> id_Item, string room, string updatedBy, string action)
        {
            var id_ItemParameter = id_Item.HasValue ?
                new ObjectParameter("Id_Item", id_Item) :
                new ObjectParameter("Id_Item", typeof(int));
    
            var roomParameter = room != null ?
                new ObjectParameter("Room", room) :
                new ObjectParameter("Room", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ass_sp", id_ItemParameter, roomParameter, updatedByParameter, actionParameter);
        }
    
        public virtual int Cancel_Request_sp(Nullable<int> id_Request, Nullable<int> id_Cart)
        {
            var id_RequestParameter = id_Request.HasValue ?
                new ObjectParameter("Id_Request", id_Request) :
                new ObjectParameter("Id_Request", typeof(int));
    
            var id_CartParameter = id_Cart.HasValue ?
                new ObjectParameter("Id_Cart", id_Cart) :
                new ObjectParameter("Id_Cart", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cancel_Request_sp", id_RequestParameter, id_CartParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> count_Status_CartItem_per_Request_sp(Nullable<int> idCart, string status)
        {
            var idCartParameter = idCart.HasValue ?
                new ObjectParameter("IdCart", idCart) :
                new ObjectParameter("IdCart", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("count_Status_CartItem_per_Request_sp", idCartParameter, statusParameter);
        }
    
        public virtual ObjectResult<damaged_items_sp_Result> damaged_items_sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<damaged_items_sp_Result>("damaged_items_sp");
        }
    
        public virtual int Delete_Item_sp(Nullable<int> id, string deleted_By, string description, string reason)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var deleted_ByParameter = deleted_By != null ?
                new ObjectParameter("Deleted_By", deleted_By) :
                new ObjectParameter("Deleted_By", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var reasonParameter = reason != null ?
                new ObjectParameter("Reason", reason) :
                new ObjectParameter("Reason", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Item_sp", idParameter, deleted_ByParameter, descriptionParameter, reasonParameter);
        }
    
        public virtual int Stocks_Per_Facility_Update_sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Stocks_Per_Facility_Update_sp");
        }
    
        public virtual int update_Barcode_sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_Barcode_sp");
        }
    
        public virtual int Update_IsGenerated_sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_IsGenerated_sp");
        }
    
        public virtual int Update_IsVerifiedField_sp(string str_Code, string updatedBy)
        {
            var str_CodeParameter = str_Code != null ?
                new ObjectParameter("Str_Code", str_Code) :
                new ObjectParameter("Str_Code", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_IsVerifiedField_sp", str_CodeParameter, updatedByParameter);
        }
    
        public virtual int Update_Item_sp(Nullable<int> id_Item, string item_Name, string serial_Number, string category, string brand_Model, string custodian, Nullable<decimal> price, string condition, string status, Nullable<int> on_Hold_Period, Nullable<System.DateTime> date_Acquisition, string remarks, string updatedBy)
        {
            var id_ItemParameter = id_Item.HasValue ?
                new ObjectParameter("Id_Item", id_Item) :
                new ObjectParameter("Id_Item", typeof(int));
    
            var item_NameParameter = item_Name != null ?
                new ObjectParameter("Item_Name", item_Name) :
                new ObjectParameter("Item_Name", typeof(string));
    
            var serial_NumberParameter = serial_Number != null ?
                new ObjectParameter("Serial_Number", serial_Number) :
                new ObjectParameter("Serial_Number", typeof(string));
    
            var categoryParameter = category != null ?
                new ObjectParameter("Category", category) :
                new ObjectParameter("Category", typeof(string));
    
            var brand_ModelParameter = brand_Model != null ?
                new ObjectParameter("Brand_Model", brand_Model) :
                new ObjectParameter("Brand_Model", typeof(string));
    
            var custodianParameter = custodian != null ?
                new ObjectParameter("Custodian", custodian) :
                new ObjectParameter("Custodian", typeof(string));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("Price", price) :
                new ObjectParameter("Price", typeof(decimal));
    
            var conditionParameter = condition != null ?
                new ObjectParameter("Condition", condition) :
                new ObjectParameter("Condition", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var on_Hold_PeriodParameter = on_Hold_Period.HasValue ?
                new ObjectParameter("On_Hold_Period", on_Hold_Period) :
                new ObjectParameter("On_Hold_Period", typeof(int));
    
            var date_AcquisitionParameter = date_Acquisition.HasValue ?
                new ObjectParameter("Date_Acquisition", date_Acquisition) :
                new ObjectParameter("Date_Acquisition", typeof(System.DateTime));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            var updatedByParameter = updatedBy != null ?
                new ObjectParameter("UpdatedBy", updatedBy) :
                new ObjectParameter("UpdatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Item_sp", id_ItemParameter, item_NameParameter, serial_NumberParameter, categoryParameter, brand_ModelParameter, custodianParameter, priceParameter, conditionParameter, statusParameter, on_Hold_PeriodParameter, date_AcquisitionParameter, remarksParameter, updatedByParameter);
        }
    
        public virtual int Update_Request_sp(Nullable<int> idRequest)
        {
            var idRequestParameter = idRequest.HasValue ?
                new ObjectParameter("IdRequest", idRequest) :
                new ObjectParameter("IdRequest", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Request_sp", idRequestParameter);
        }
    }
}
