//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCISM_WBRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Junk_Item
    {
        public int Id { get; set; }
        public string Str_Code { get; set; }
        public string Str_Code_Display { get; set; }
        public string Item_Name { get; set; }
        public Nullable<System.DateTime> Date_Deleted { get; set; }
        public string Deleted_By { get; set; }
        public string Description { get; set; }
        public string Reason { get; set; }
    }
}
