//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCISM_WBRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_vw
    {
        public int Id_Request { get; set; }
        public int Id_Transaction { get; set; }
        public int Id_Cart { get; set; }
        public string Date_Want_To_Receive { get; set; }
        public string Date_Expected_Return { get; set; }
        public string Purpose { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public string formatted_transac_date { get; set; }
        public string Requestor_Name { get; set; }
        public string Id_Number { get; set; }
        public string Secret_Code { get; set; }
        public string Requestor_Full_Name { get; set; }
        public string User_Type { get; set; }
    }
}
