//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCISM_WBRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Signup
    {
        public int Id { get; set; }
        public string ID_Number { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Middle_Name { get; set; }
        public string CourseAndYear { get; set; }
        public string Email_Add { get; set; }
        public string Address { get; set; }
        public string Contact_No { get; set; }
        public Nullable<bool> Is_Email_Confirm { get; set; }
        public Nullable<bool> Is_Contact_No_Confirm { get; set; }
        public string Code_Generated { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string UserType { get; set; }
        public string Signup_Date { get; set; }
    }
}
