//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCISM_WBRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Id_Cart { get; set; }
        public string Requestor_Name { get; set; }
        public string Id_Number { get; set; }
        public string Secret_Code { get; set; }
    }
}
