//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCISM_WBRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSubCategory
    {
        public int Id_SubCategory { get; set; }
        public int Id_Category { get; set; }
        public string SubCategory_Name { get; set; }
        public string Description { get; set; }
    }
}
