//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCISM_WBRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_History
    {
        public int Id { get; set; }
        public Nullable<int> Id_Item { get; set; }
        public string Str_Code { get; set; }
        public string Action { get; set; }
        public string Action_History_Desc { get; set; }
        public Nullable<System.DateTime> Action_Date { get; set; }
        public string Done_By { get; set; }
        public Nullable<System.DateTime> Borrowed_Date { get; set; }
        public string Borrowed_By { get; set; }
        public Nullable<System.DateTime> Released_Date { get; set; }
        public string Released_To { get; set; }
        public string Condition_Before_Released { get; set; }
        public string Remarks_Before_Released { get; set; }
        public string Returned_Date { get; set; }
        public string Condition_After_Returned { get; set; }
        public string Remarks_After_Returned { get; set; }
        public Nullable<bool> Is_Current_Borrowed_Trans { get; set; }
        public Nullable<bool> Is_Current_Released_Trans { get; set; }
        public Nullable<bool> Is_Current_Returned_Trans { get; set; }
        public Nullable<System.DateTime> Expected_Date_Of_Return { get; set; }
    }
}
