//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCISM_WBRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id_Transaction { get; set; }
        public string ID_Number { get; set; }
        public string Transaction_Type { get; set; }
        public string Purpose { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Is_Approved { get; set; }
        public Nullable<System.DateTime> Approved_Date { get; set; }
        public string Approved_By { get; set; }
        public string Secret_Code { get; set; }
    }
}
