//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCISM_WBRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Details_vw
    {
        public int Id { get; set; }
        public string ID_Number { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool Is_Active { get; set; }
        public int ID_Role { get; set; }
        public string Status { get; set; }
        public string RF { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Middle_Name { get; set; }
        public string CourseAndYear { get; set; }
        public string Email_Add { get; set; }
        public string Address { get; set; }
        public string Contact_No { get; set; }
        public string Role_Name { get; set; }
    }
}
